language: python

python:
  - 2.7
  - 3.4

virtualenv:
    system_site_packages: true

env: # see https://docs.travis-ci.com/user/languages/python/#testing-against-multiple-versions-of-dependencies-eg-django-or-flask
  - NETWORKX_VERSION=1.11
  - NETWORKX_VERSION=2.2

install:
  - pip install coveralls
  - pip install pep8
  # test both networkx 1.11 and 2.2
  - pip install -q networkx==$NETWORKX_VERSION
  # need the following installed from their respective github repos
  # to ensure that the latest version of numpy and scipy are installed;
  # causes errors in the TravisCI framework otherwise
  # downside: TravisCI now takes ~20-25 minutes to finish its run
  - sudo apt-get install libatlas-base-dev gfortran
  - pip install git+http://github.com/cython/cython.git@0.20.x
  - pip install git+http://github.com/numpy/numpy/
  - pip install git+http://github.com/scipy/scipy/
  - pip install git+http://github.com/scipy/scipy.git@maintenance/0.14.x

script:
  - pep8 halp
  - coverage run --source=halp setup.py test

after_success:
    coveralls
