language: python

python:
  - 3.2

virtualenv:
    system_site_packages: true

install:
  - pip install coveralls
  - pip install pep8
  - pip install networkx
  - pip install cython
  - pip install numpy
  - sudo apt-get install python3-scipy

script:
  - pep8 halp
  - coverage run --source=halp setup.py test

after_success:
    coveralls
